@echo off
echo Starting Internal CAASM Portal...
echo =================================
cd backend
echo Checking local database migrations...
:: Since this is an MVP without Alembic setup for simplicity, we just rely on Base.metadata.create_all
echo Starting FastAPI Backend...
..\venv\Scripts\python.exe -m uvicorn app.main:app --host 127.0.0.1 --port 8000
